# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d34a1ba9b81a8d1c7af971956be19b41d0db955fe0c644db9a020291563dc2e67be0bbff8533c31ac00b2984f1f28298ee054a1605d0798e746e7416cc28741

test:
  secret_key_base: 2c3d6ef107228ccd57555f3eeba8934ccebdb8d959cd62d4327906f9a27b8194303a7a31d2ec5ab92e5e700dca9e931613a25066cf6af8c7ad4122a35683de13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
